### ISSUE TITLE
CLI: show tokens in auth headers

### ISSUE THREAD

**Issue by skovranek** [bootdotdev/bootdev#15]
Before the awesome bootdev cli tool, users could see "jwtToken1" variables be replaced with the actual token in the feedback. This was a fairly recent change that all but eliminated reports that the tests were broken. Users see the "jwtToken1" in the request and assume the problem is the test instead of their faulty code.

If the CLI doesn't already, is it maybe worth considering possibly adding this to the bootdev CLI someday?

Example report about "broken tests" because users don't realize their code is wrong:

https://github.com/bootdotdev/courses/issues/6894

### Example CLI response missing interpolation:

<img width="552" alt="Screenshot 2024-05-05 at 11 28 56 PM" src="https://github.com/bootdotdev/bootdev/assets/59619403/386473ea-bbb4-4a51-9fd6-2593483a3d75">

### Example client response missing interpolation:

<img width="493" alt="Screenshot 2024-05-05 at 11 31 25 PM" src="https://github.com/bootdotdev/bootdev/assets/59619403/8f1df7a2-883a-4f12-8753-53363eb43b39">

**Comment by wagslane** [comment]
Yes, let's update the CLI to show the actual token post-interpolation in the console
