### ISSUE TITLE
CLI improve go to next lesson flow

### ISSUE THREAD

**Issue by wagslane** [bootdotdev/bootdev#16]
From Prime:

> when finishing the lesson, going to the next should potentially be more "obvious"
especially when you are using the CLI for completing the lesson

My thoughts are that when the CLI detects that you got the "correct" submission its final lines should say something like "Correct! Click here to go to the next lesson: *link*"

Again, would like to hear thoughts from @cgsdev0 before we pull the trigger

**Comment by cgsdev0** [comment]
Closed by a775133fe5a3c91643b920055fe82fae0297d908
