### ISSUE TITLE
Minor issue in README.md for Mac OS .bashrc

### ISSUE THREAD

**Issue by rachyrachyrach** [bootdotdev/bootdev#18]
https://github.com/bootdotdev/bootdev/blob/main/README.md

![Screenshot 2024-05-14 at 1 01 45 PM](https://github.com/bootdotdev/bootdev/assets/81942023/fddb45b7-4162-4f10-a151-50522b8804f6)

Not sure if this is for all Macs.  For the section in the readme on "Next, reload your shell configuration:" I had to use command `source ~/.zshrc` instead of the '.bashrc' file.

**Comment by cgsdev0** [comment]
updated to make this clearer. thanks!
