### ISSUE TITLE
Add option to submit if `bootdev run` is successful

### ISSUE THREAD

**Issue by evilhamsterman** [bootdotdev/bootdev#22]
It's annoying if your `bootdev run` succeeded to have to either retype, use your history and modify, etc to subsequently run `bootdev submit`. I would be a nice QoL if when a run succeeds you are prompted if you want to submit and/or add a flag to submit on a successful run.

**Comment by EMBradley** [comment]
As I understand it, it's supposed to be on you as the user/learner to determine whether `bootdev run` was successful or not. Even if it exits with code 0, that doesn't necessarily mean that it succeeded. You're supposed to check that the output was what was expected before submitting.

**Comment by skovranek** [comment]
the -s flag was added to let you do this! 

submit:
`bootdev run <lesson_id> -s`
