### ISSUE TITLE
Build release binaries

### ISSUE THREAD

**Issue by evilhamsterman** [bootdotdev/bootdev#23]
I see several questions about installing using the `go install` command. Since just setting up a go environment is part of one of the courses that's after the point where you start using the `bootdev` command I think it would make sense to simply build binaries for people to download and copy to their local PATH

**Comment by cgsdev0** [comment]
the reason we have held off on this so far is because signing macOS binaries is complicated:tm:

we'd like to do it eventually, but since people need to install go for the later courses anyways, we made this tradeoff for now
