### ISSUE TITLE
Verify Go Version

### ISSUE THREAD

**Issue by mdwiltfong** [bootdotdev/bootdev#33]
It would be helpful if the CLI could notify the user that they are potentially using an outdated version Go. 

For example, in [this lesson](https://www.boot.dev/lessons/174d13f0-f887-46c6-a633-d963662fde39) I spent a lot of time trying to debug why the tests were failing only to find a hint in the Discord that maybe my Go version was the issue. I was using 1.21 when upgrading it to 1.22.5 resolved the issue. 

I think it would be beneficial to offer a command to check this, and then potentially update the lessons to guide learners to use this command.

**Comment by skovranek** [comment]
Now the CLI forces people to upgrade for minor versions. Thank you for reporting this.
