### ISSUE TITLE
wrong colors for test after failed test

### ISSUE THREAD

**Issue by skovranek** [bootdotdev/bootdev#36]
﻿## What﻿
﻿
﻿The first test correctly fails, then the second test shows green and grey. My guess is that the intention is for a failed test to prevent further tests from running, right? So the green on the second test should be grey?
﻿
<img width="777" alt="Screenshot 2024-07-09 at 1 36 58 AM" src="https://github.com/bootdotdev/bootdev/assets/59619403/d1491441-dc62-43cc-b953-6366e8b6704a">

**Comment by cgsdev0** [comment]
uh oh

I wonder if we had a regression when we added the http test renderer

i will investigate
