### ISSUE TITLE
New version available message after running bootdev upgrade

### ISSUE THREAD

**Issue by edbar42** [bootdotdev/bootdev#44]
I have logged on a machine that I haven't used for a while and, naturally, was asked to run `bootdev upgrade` when running tests for a lesson. I got the following output:

```
$ bootdev upgrade
Successfully upgraded to v1.7.0!
A new version of the bootdev CLI is available!
Please run the following command to update:
  bootdev upgrade
```

When running `bootdev upgrade` again:

```
$ bootdev upgrade
Boot.dev CLI is already up to date.
```

I saw that something similar to this was addressed in the commit history, so maybe this is the last time I get this output when running `upgrade`?

**Comment by cgsdev0** [comment]
this has already been fixed. thanks for the report!
