### ISSUE TITLE
GOPROXY edge cases

### ISSUE THREAD

**Issue by skovranek** [bootdotdev/bootdev#49]
per discord:
https://discord.com/channels/551921866173054977/1277003758450114580/1277003758450114580

possible unhandled edge cases:
1. no GOPROXY: ""
2. only "direct" GOPROXY

**Comment by Asfolny** [comment]
I had some fun looking into this
As of go 1.13, default GORPOXY (unset GOPROXY and GOPROXY="") is set to `https://proxy.golang.org,direct`, and the version check still works on go 1.22.6 (not tested against 1.23)
What also works is against conforming proxies like
- https://goproxy.io
- https://goproxy.cn

Specifically what doesn't work is `GOPROXY=direct` and `GOPROXY=off`

Fully respecting GOPROXY doesn't seem like a viable solution, and GOPROXY=off means "no network"

What would be the easiest fix is checking if the proxy list contains `https://proxy.golang.org` and if not, append it to the proxies list like this:
```patch
diff --git a/version/version.go b/version/version.go
index 1eb8093..4292aa8 100644
--- a/version/version.go
+++ b/version/version.go
@@ -7,6 +7,7 @@ import (
 	"net/http"
 	"os"
 	"os/exec"
+	"slices"
 	"strings"

 	"golang.org/x/mod/semver"
@@ -63,7 +64,8 @@ func isUpdateRequired(current string, latest string) bool {
 }

 func getLatestVersion() (string, error) {
-	goproxy := "https://proxy.golang.org"
+	goproxyDefault := "https://proxy.golang.org"
+	goproxy := goproxyDefault
 	cmd := exec.Command("go", "env", "GOPROXY")
 	output, err := cmd.Output()
 	if err == nil {
@@ -71,14 +73,18 @@ func getLatestVersion() (string, error) {
 	}

 	if goproxy == "" {
-		goproxy = "https://proxy.golang.org"
+		goproxy = goproxyDefault
 	}

 	proxies := strings.Split(goproxy, ",")
+	if !slices.Contains(proxies, goproxyDefault) {
+		proxies = append(proxies, goproxyDefault)
+	}
+
 	for _, proxy := range proxies {
 		proxy = strings.TrimSpace(proxy)
 		proxy = strings.TrimRight(proxy, "/")
-		if proxy == "direct" {
+		if proxy == "direct" || proxy == "off" {
 			continue
 		}
```

It would also be possible to expose an API from something like `api.boot.dev/github.com/bootdotdev/bootdev/@latest` and simply return the version from there

As a last mention: the github api
- The releases feature (the version would be the tag name, available as `tag_name` in json, so it would still not quite fit the current code's `Version` Unmarshall, see [here](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release))
- Using tags, which returns an array, grab the first and use the name as the version ([api docs for tags](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-tags))

**Comment by Asfolny** [comment]
Just found out why on Fedora it doesn't work, fedora's RPM package has a patch that changes GOPROXY to `direct`
