### ISSUE TITLE
Stuck in upgrade loop

### ISSUE THREAD

**Issue by rkapu** [bootdotdev/bootdev#58]
Upon trying to submit a task, I was presented with a requirement to upgrade the CLI tool.

<img width="609" alt="Screenshot 2024-09-29 at 13 51 51" src="https://github.com/user-attachments/assets/c89da194-e0a5-4820-a422-4037f4a91195">

After running upgrade command, I was still on the same version as before and kept receiving a message that upgrade is available when running bootdev command.
<img width="567" alt="Screenshot 2024-09-29 at 13 51 24" src="https://github.com/user-attachments/assets/c40df72a-1cf4-41ae-86b7-76537dbc9379">

I'm using `asdf` as runtime versions manager.

**Comment by rkapu** [comment]
Removing and installing the package with `go install` command didn't help.

**Comment by rkapu** [comment]
Isn't upgrade optional though?
Or is it required when new major versions come out?

**Comment by epzeller** [comment]
I am also stuck in the upgrade loop.  When I try and submit my code I am told:

> A new version of the bootdev CLI is available!
> Please run the following command to update:
>  bootdev upgrade

I run bootdev upgrade
> Successfully upgraded to v1.7.1!

And then I get the same error as before.

**Comment by skovranek** [comment]
Is this error still persisting?

IIRC, the fix maybe to run the go install command manually:

`go install github.com/bootdotdev/bootdev@latest`

If that doesn't work, manually remove the binary after using which to find its location and try again: `which bootdev`

**Comment by rkapu** [comment]
> Is this error still persisting?
> 
> IIRC, the fix maybe to run the go install command manually:
> 
> `go install github.com/bootdotdev/bootdev@latest`
> 
> If that doesn't work, manually remove the binary after using which to find its location and try again: `which bootdev`

Had to upgrade again recently. This time all went smooth.
Upgraded with `bootdev upgrade` and then `asdf reshim golang`.
No issues this time.

I will close the ticket.
Thanks.
