### ISSUE TITLE
Update prompt in shell completion script

### ISSUE THREAD

**Issue by thiagocamargodacosta** [bootdotdev/bootdev#6]
Hi there,

I have noticed a behavior in the bootdev CLI that might be worth addressing. When running a version of the CLI other than the latest and issuing the `bootdev completion bash` command, the update prompt gets prepended to the shell completion script.

While I'm not entirely sure if this qualifies as an issue, I believe adding the following check to the `Execute` function inside `root.go` could prevent this behavior:

```go
func Execute() {
    if len(os.Args) > 1 && os.Args[1] == "completion" {
        err := rootCmd.Execute()
        cobra.CheckErr(err)
        if err != nil {
            os.Exit(1)
        }
        return
    }
    err := checks.PromptUpdateIfNecessary(rootCmd.Version)
    // ...
}
```

By incorporating this check before the `PromptUpdateIfNecessary` call, we might avoid the update prompt appearing in the shell completion script.

Would it be worthwhile to make this modification to the source code? If so, I would be more than willing to provide additional information for a more suitable solution or, if this check suffices, create a pull request.

Looking forward to your thoughts on this.

Kind regards,
Thiago

**Comment by cgsdev0** [comment]
hi!

I have moved the update messages to `stderr` instead of `stdout`, so they shouldn't get added to the completions anymore

this should be available now in v1.2.2+
