### ISSUE TITLE
Response headers are not displayed

### ISSUE THREAD

**Issue by Demianeen** [bootdotdev/bootdev#8]
When I run bootdev cli I don't see headers. For example for [routing lesson](https://www.boot.dev/assignments/d1c4962d-f55e-4f0f-ac9c-913db8ef8ae8):
![CleanShot 2024-05-01 at 09 53 23@2x](https://github.com/bootdotdev/bootdev/assets/51330172/b093b068-9f79-4a27-936e-2cad22a24753)

I can see headers in any other rest clients. Also, the lesson submission does work.

![CleanShot 2024-05-01 at 09 56 40@2x](https://github.com/bootdotdev/bootdev/assets/51330172/39ab9a6d-5c02-4cce-9908-ff83ee0006a2)

**Comment by cgsdev0** [comment]
we filter the headers to only show the ones being tested for

the behavior is kinda confusing, I will try to see if I can think of a way to make it more obvious 👍

**Comment by Demianeen** [comment]
Sure. As an idea, I think you can highlight the headers that are being tested

**Comment by Waldeedle** [comment]
![image](https://github.com/bootdotdev/bootdev/assets/92062428/970ce112-1351-4346-b43f-d26f967fcda0)

Would something like this make sense? We iterate through the result headers and use lipgloss to style any matches from the expected headers as green otherwise output them as grey. Then we can also loop through the expected headers and output any missing ones as red.
```golang
		for k, v := range result.Headers {
			if req.Request.Headers[k] == v {
				fmt.Print(green.Render(fmt.Sprintf("   - %v: %v", k, v)) + "\n")
			} else {
				fmt.Printf(gray.Render(fmt.Sprintf("   - %v: %v", k, v)) + "\n")
			}
		}
		for k, v := range req.Request.Headers {
			if _, found := result.Headers[k]; !found {
				fmt.Printf(red.Render(fmt.Sprintf("   - %v: %v", k, v)) + "\n")
			}
		}
```

**Comment by cgsdev0** [comment]
@Waldeedle that looks nice!

I'm going to rewrite the render functions for the HTTP tests soon to match the fancy ones we have for the commands now, I'll keep this idea in mind
